### ISSUE TITLE
locale issues on 3.4.0 image

### ISSUE THREAD

**Issue by MichaelChirico** [r-hub/evercran#11]
I was able to build and launch `ghcr.io/r-hub/evercran/3.4.0` with ease, however now I'm seeing some persistent issues with locale I can't seem to squash:

```shell
R CMD INSTALL .
# ...
# During startup - Warning messages:
# 1: Setting LC_CTYPE failed, using "C" 
# 2: Setting LC_COLLATE failed, using "C" 
# 3: Setting LC_TIME failed, using "C" 
# 4: Setting LC_MESSAGES failed, using "C" 
# 5: Setting LC_MONETARY failed, using "C" 
# 6: Setting LC_PAPER failed, using "C" 
# 7: Setting LC_MEASUREMENT failed, using "C" 
# ...
```

I have tried many combinations of `locale-gen`, `apt-get install locales`, `dpkg-reconfigure locales`, `update-locale`, editing `/etc/locale.gen`, but I'm consistently unable to get anything working, e.g. continue seeing

```shell
# bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

This is an annoyance as much as anything, but it would be nice to have a fix here.

**Comment by gaborcsardi** [comment]
Here is an example from https://github.com/r-hub/containers/blob/3d1e1581f8bc0d8b7d90ab59069afe8ca2659506/containers/ubuntu-next/Dockerfile#L64-L74:

```dockerfile
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && \
    apt-get install -y locales && \
    apt-get clean && \
    locale-gen en_GB.UTF-8 en_US.UTF-8 && \
    update-locale
ENV LC_COLLATE C
ENV LANG en_GB.UTF-8
```

IDK if we should add this to the images.

**Comment by MichaelChirico** [comment]
I may revisit this eventually but it's off my radar for now, closing so it's out of your hair. Thanks for the tip!
