### ISSUE TITLE
Add a single build for 3.x and/or 4.x

### ISSUE THREAD

**Issue by hughjonesd** [r-hub/evercran#6]
It would be very helpful to have a single build with 3.x and 4.x versions, as there are for pre, 0.x, 1.x and 2.x.

I'm gonna move [rcheology](https://github.com/hughjonesd/rcheology) over to this... really feeling the pain of non-reproducibility as old Docker recipes fail to reproduce :-(

**Comment by gaborcsardi** [comment]
Unfortunately those images would be very big, several GB, that's why I didn't do that.

**Comment by gaborcsardi** [comment]
Yes, the 2.x image is already ~ 2GB, and 3.x and 4.x installations are much bigger, so I am going to close this now.
