### ISSUE TITLE
R 0.60 segfaults

### ISSUE THREAD

**Issue by hughjonesd** [r-hub/evercran#8]
On arm64 host:

```
a3eac92eaa73:~# /opt/R/0.60/bin/R

R : Copyright 1997, Robert Gentleman and Ross Ihaka
Version 0.60 Alpha (December 2, 1997)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type    "license()" for details.

Type    "demo()" for some demos, "help()" for on-line help, or
        "help.start()" for a HTML browser interface to help.

qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

**Comment by gaborcsardi** [comment]
Unfortunately that's a Docker/qemu bug, not much we can do, but use an x86_64 host.

**Comment by hughjonesd** [comment]
Actually I get the same issue on my amd64 Mac when using `--platform linux/i386`.

**Comment by gaborcsardi** [comment]
Hmmm, I think I have seen this and it is patched for some versions already. Something like this instead of the original code in `library/base/R/Rprofile` fixes it:
```
.Library <- paste(getenv("RHOME"), "library", sep = "/")
if (getenv("RLIBS") != "") {
  .lib.loc <- unique(c(unlist(strsplit(getenv("RLIBS"), ":")), .Library))
} else {
  .lib.loc <- .Library
}
```

**Comment by gaborcsardi** [comment]
Oh, here is an example patch: https://github.com/r-hub/evercran/blob/ac710f6d12d3ba6687cdb414d138c7b2a971d6f2/r-builds/patch/R-0.50-a4.patch#L29-L37

I'll apply that to 0.60.

**Comment by gaborcsardi** [comment]
Should be fixed now, works on arm64 macOS as well. Please reopen if you see problems. Thanks!

**Comment by hughjonesd** [comment]
This fixes 0.60 but 0.60.1 still segfaults, could you apply the same fix there?

**Comment by gaborcsardi** [comment]
Sure.

**Comment by gaborcsardi** [comment]
Done.

**Comment by hughjonesd** [comment]
Ping when you've run the github action.

**Comment by gaborcsardi** [comment]
For 0.x? I forgot that, but done now.
