### ISSUE TITLE
Xvfb hell

### ISSUE THREAD

**Issue by hughjonesd** [r-hub/evercran#9]
This isn't strictly a bug you should have to deal with, but I'm reaching out just because you might have a clue... I'm stuck.

I want to use Xvfb to provide an X server so that I can run `library(tcltk)` in R. Before 2.8.0 this required an X server to be available, or the package would not load.

For 2.x this works fine:

```
apt-get install -y -q r-base-dev tcl8.4-dev tk8.4-dev \
    xvfb xbase-clients x-window-system-core
/usr/bin/Xvfb :0 -ac -screen 0 1960x2000x24 & 
```

But on 1.x,  I get:

```
/usr/X11R6/bin/Xvfb :0 -ac -screen 0 1960x2000x24 

Could not init font path element /usr/X11R6/lib/X11/fonts/CID/, removing from list!

Fatal server error:
could not open default font 'fixed';
the X server's font paths might be misconfigured, remote font server(s)
may be unreachable, and/or local fonts may not be installed or are not
configured correctly.

People inexperienced with the X Window System should have either the
"x-window-system" or "x-window-system-core" packages installed.
# apt-get install x-window-system-core
# apt-get install x-window-system

Other useful commands to run include:
$ dpkg --status xserver-common
$ dpkg --status xfonts-base
$ zmore /usr/share/doc/xfree86-common/FAQ.gz
```

I have the same debian packages installed, as it suggests. I also tried copying /usr/X11R6/lib/X11 to a bind mount on the host, which worked for /opt/R on this platform. But no luck.

I'm pretty lost with X11 and ancient Debian; just wondered if you had any ideas.

**Comment by gaborcsardi** [comment]
I am sorry. I spent many a sleepless night trying to install fonts and configure x servers some years ago. I surely hoped that those days were over. :(

Maybe it is possible to open a port in docker and use an external x server?

**Comment by gaborcsardi** [comment]
E.g. something like https://gursimarsm.medium.com/run-gui-applications-in-a-docker-container-ca625bad4638 ?

I actually could not get this to work, but haven't (yet) tried very hard, and in theory it definitely should work.

**Comment by gaborcsardi** [comment]
OK, this works on macOS:
1. Start XQuartz
2. In Settings / Security untick "Authenticate Connections" and tick "Allow connections from network clients"
3. Restart XQuartz (this might not be needed)
4. In a terminal run `xhost +` (it is possible that this is not needed in macOS)
5. Start docker container like this:
```
docker run -it --platform linux/i386 -e DISPLAY=host.docker.internal:0 ghcr.io/r-hub/evercran/0.60 bash
```

After this `x11()` etc. should work in R.

If you run this a lot, then it makes sense to add authentication.

**Comment by hughjonesd** [comment]
This worked! Thanks for your help, buddy. We now have tcltk data for 1.2 to 1.9.1!

**Comment by gaborcsardi** [comment]
Cool. Btw. XQuartz also has Xvfb, and it also works, you need to run this on macOS:
```
Xvfb :1 -listen tcp
```
and then you use the `:1` display in the container:
```
docker run -it -e DISPLAY=host.docker.internal:1 ghcr.io/r-hub/evercran/1.6.0 bash
```

This also does not seem to have authentication. It is also possible to use `xauth` to set this up with authentication, but it is a bit cumbersome, because `xauth add` cannot add host.docker.internal on the host because it tries to resolve the host name.

**Comment by hughjonesd** [comment]
That's great. Actually means I can now run everything from a single shell script.
